"""xPyD-plan: PD ratio planner for xPyD proxy."""

__version__ = "0.2.0"

from xpyd_plan.alerting import (
    AlertEngine,
    AlertReport,
    AlertResult,
    AlertRule,
    AlertSeverity,
    Comparator,
    evaluate_alerts,
)
from xpyd_plan.analyzer import BenchmarkAnalyzer
from xpyd_plan.annotation import (
    AnnotatedBenchmark,
    Annotation,
    AnnotationManager,
    FilterResult,
    annotate_benchmark,
)
from xpyd_plan.benchmark_models import (
    AnalysisResult,
    BenchmarkData,
    BenchmarkMetadata,
    BenchmarkRequest,
    RatioCandidate,
    SLACheck,
    UtilizationResult,
)
from xpyd_plan.budget import (
    AllocationStrategy,
    BudgetAllocation,
    BudgetAllocator,
    StageBudget,
    allocate_budget,
)
from xpyd_plan.comparator import (
    BenchmarkComparator,
    ComparisonResult,
    MetricDelta,
    compare_benchmarks,
)
from xpyd_plan.confidence import (
    Adequacy,
    ConfidenceAnalyzer,
    ConfidenceInterval,
    ConfidenceReport,
    MetricConfidence,
    analyze_confidence,
)
from xpyd_plan.config import ConfigProfile, load_config
from xpyd_plan.dashboard import (
    Dashboard,
    DashboardState,
    DashboardView,
    run_dashboard,
)
from xpyd_plan.filter import (
    BenchmarkFilter,
    BenchmarkFilterResult,
    FilterConfig,
    filter_benchmark,
)
from xpyd_plan.fleet import (
    FleetAllocation,
    FleetCalculator,
    FleetOption,
    FleetReport,
    GPUTypeConfig,
    calculate_fleet,
)
from xpyd_plan.generator import (
    AnomalyConfig,
    AnomalyType,
    BenchmarkGenerator,
    DistributionType,
    GeneratorConfig,
    LatencyProfile,
    generate_benchmark,
    load_generator_config,
)
from xpyd_plan.gpu_profiles import get_gpu_profile, list_gpu_profiles
from xpyd_plan.interpolator import (
    InterpolationConfidence,
    InterpolationMethod,
    InterpolationResult,
    PerformanceInterpolator,
    PredictedPerformance,
    interpolate_performance,
)
from xpyd_plan.md_report import (
    MarkdownReportConfig,
    MarkdownReporter,
    generate_markdown_report,
)
from xpyd_plan.merger import (
    BenchmarkMerger,
    MergeConfig,
    MergeResult,
    MergeStrategy,
    merge_benchmarks,
)
from xpyd_plan.models import (
    DatasetStats,
    GPUProfile,
    PDConfig,
    SLAConfig,
)
from xpyd_plan.pareto import (
    ParetoAnalyzer,
    ParetoCandidate,
    ParetoFrontier,
    ParetoObjective,
    find_pareto_frontier,
)
from xpyd_plan.pipeline import (
    PipelineConfig,
    PipelineResult,
    PipelineRunner,
    PipelineStep,
    StepResult,
    StepType,
    load_pipeline_config,
    run_pipeline,
)
from xpyd_plan.recommender import (
    ActionCategory,
    Recommendation,
    RecommendationEngine,
    RecommendationPriority,
    RecommendationReport,
    get_recommendations,
)
from xpyd_plan.trend import TrendEntry, TrendReport, TrendTracker, track_trend
from xpyd_plan.validator import (
    DataQualityScore,
    DataValidator,
    OutlierMethod,
    ValidationResult,
    validate_benchmark,
)

__all__ = [
    "AnnotatedBenchmark",
    "Annotation",
    "AnnotationManager",
    "FilterResult",
    "annotate_benchmark",
    "AlertEngine",
    "AlertReport",
    "AlertResult",
    "AlertRule",
    "AlertSeverity",
    "Comparator",
    "evaluate_alerts",
    "AnalysisResult",
    "BenchmarkAnalyzer",
    "BenchmarkComparator",
    "ComparisonResult",
    "MetricDelta",
    "compare_benchmarks",
    "Adequacy",
    "ConfidenceAnalyzer",
    "ConfidenceInterval",
    "ConfidenceReport",
    "MetricConfidence",
    "analyze_confidence",
    "BenchmarkData",
    "BenchmarkMetadata",
    "BenchmarkRequest",
    "ConfigProfile",
    "DatasetStats",
    "GPUProfile",
    "PDConfig",
    "ParetoAnalyzer",
    "ParetoCandidate",
    "ParetoFrontier",
    "ParetoObjective",
    "find_pareto_frontier",
    "RatioCandidate",
    "SLACheck",
    "SLAConfig",
    "UtilizationResult",
    "get_gpu_profile",
    "list_gpu_profiles",
    "load_config",
    "track_trend",
    "TrendEntry",
    "TrendReport",
    "TrendTracker",
    "DataQualityScore",
    "DataValidator",
    "OutlierMethod",
    "ValidationResult",
    "validate_benchmark",
    "InterpolationConfidence",
    "InterpolationMethod",
    "InterpolationResult",
    "PerformanceInterpolator",
    "PredictedPerformance",
    "interpolate_performance",
    "Dashboard",
    "DashboardState",
    "DashboardView",
    "run_dashboard",
    "ActionCategory",
    "Recommendation",
    "RecommendationEngine",
    "RecommendationPriority",
    "RecommendationReport",
    "get_recommendations",
    "FleetAllocation",
    "FleetCalculator",
    "FleetOption",
    "FleetReport",
    "GPUTypeConfig",
    "calculate_fleet",
    "PipelineConfig",
    "PipelineResult",
    "PipelineRunner",
    "PipelineStep",
    "StepResult",
    "StepType",
    "load_pipeline_config",
    "run_pipeline",
    "MarkdownReportConfig",
    "MarkdownReporter",
    "generate_markdown_report",
    "BenchmarkMerger",
    "MergeConfig",
    "MergeResult",
    "MergeStrategy",
    "merge_benchmarks",
    "AnomalyConfig",
    "AnomalyType",
    "BenchmarkGenerator",
    "DistributionType",
    "GeneratorConfig",
    "LatencyProfile",
    "generate_benchmark",
    "load_generator_config",
    "AllocationStrategy",
    "BudgetAllocation",
    "BudgetAllocator",
    "StageBudget",
    "allocate_budget",
    "BenchmarkFilter",
    "BenchmarkFilterResult",
    "FilterConfig",
    "filter_benchmark",
]
