"""xPyD-plan: PD ratio planner for xPyD proxy."""

__version__ = "0.2.0"

from xpyd_plan.ab_test import (
    ABConfidenceInterval,
    ABTestAnalyzer,
    ABTestConfig,
    ABTestReport,
    ABTestResult,
    EffectMagnitude,
    EffectSize,
    PowerWarning,
    StatisticalTest,
    analyze_ab_test,
)
from xpyd_plan.alerting import (
    AlertEngine,
    AlertReport,
    AlertResult,
    AlertRule,
    AlertSeverity,
    Comparator,
    evaluate_alerts,
)
from xpyd_plan.analyzer import BenchmarkAnalyzer
from xpyd_plan.annotation import (
    AnnotatedBenchmark,
    Annotation,
    AnnotationManager,
    FilterResult,
    annotate_benchmark,
)
from xpyd_plan.benchmark_models import (
    AnalysisResult,
    BenchmarkData,
    BenchmarkMetadata,
    BenchmarkRequest,
    RatioCandidate,
    SLACheck,
    UtilizationResult,
)
from xpyd_plan.budget import (
    AllocationStrategy,
    BudgetAllocation,
    BudgetAllocator,
    StageBudget,
    allocate_budget,
)
from xpyd_plan.cdf import (
    CDFCurve,
    CDFGenerator,
    CDFPoint,
    CDFReport,
    SLAMarker,
    generate_cdf,
)
from xpyd_plan.comparator import (
    BenchmarkComparator,
    ComparisonResult,
    MetricDelta,
    compare_benchmarks,
)
from xpyd_plan.confidence import (
    Adequacy,
    ConfidenceAnalyzer,
    ConfidenceInterval,
    ConfidenceReport,
    MetricConfidence,
    analyze_confidence,
)
from xpyd_plan.config import ConfigProfile, load_config
from xpyd_plan.convergence import (
    ConvergenceAnalyzer,
    ConvergencePoint,
    ConvergenceReport,
    MetricConvergence,
    StabilityStatus,
    analyze_convergence,
)
from xpyd_plan.correlation import (
    CorrelationAnalyzer,
    CorrelationPair,
    CorrelationReport,
    CorrelationStrength,
    analyze_correlation,
)
from xpyd_plan.dashboard import (
    Dashboard,
    DashboardState,
    DashboardView,
    run_dashboard,
)
from xpyd_plan.decomposer import (
    BottleneckType,
    DecomposedRequest,
    DecompositionReport,
    LatencyDecomposer,
    PhaseStats,
    decompose_latency,
)
from xpyd_plan.discovery import (
    BenchmarkDiscovery,
    ConfigGroup,
    DiscoveredBenchmark,
    DiscoveryReport,
    ValidationStatus,
    discover_benchmarks,
)
from xpyd_plan.drift import (
    DriftDetector,
    DriftReport,
    DriftResult,
    DriftSeverity,
    detect_drift,
)
from xpyd_plan.fairness import (
    BucketStats,
    FairnessAnalyzer,
    FairnessClassification,
    FairnessIndex,
    FairnessReport,
    analyze_fairness,
)
from xpyd_plan.filter import (
    BenchmarkFilter,
    BenchmarkFilterResult,
    FilterConfig,
    filter_benchmark,
)
from xpyd_plan.fleet import (
    FleetAllocation,
    FleetCalculator,
    FleetOption,
    FleetReport,
    GPUTypeConfig,
    calculate_fleet,
)
from xpyd_plan.forecaster import (
    CapacityExhaustion,
    CapacityForecaster,
    ForecastMethod,
    ForecastPoint,
    ForecastReport,
    forecast_capacity,
)
from xpyd_plan.generator import (
    AnomalyConfig,
    AnomalyType,
    BenchmarkGenerator,
    DistributionType,
    GeneratorConfig,
    LatencyProfile,
    generate_benchmark,
    load_generator_config,
)
from xpyd_plan.gpu_profiles import get_gpu_profile, list_gpu_profiles
from xpyd_plan.health_check import (
    CheckResult,
    HealthChecker,
    HealthReport,
    HealthStatus,
    check_health,
)
from xpyd_plan.heatmap import (
    AggregationMetric,
    HeatmapCell,
    HeatmapConfig,
    HeatmapGenerator,
    HeatmapGrid,
    HeatmapReport,
    LatencyField,
    generate_heatmap,
)
from xpyd_plan.interpolator import (
    InterpolationConfidence,
    InterpolationMethod,
    InterpolationResult,
    PerformanceInterpolator,
    PredictedPerformance,
    interpolate_performance,
)
from xpyd_plan.load_profile import (
    LoadProfile,
    LoadProfileClassifier,
    LoadProfileReport,
    ProfileType,
    RateWindow,
    classify_load_profile,
)
from xpyd_plan.md_report import (
    MarkdownReportConfig,
    MarkdownReporter,
    generate_markdown_report,
)
from xpyd_plan.merger import (
    BenchmarkMerger,
    MergeConfig,
    MergeResult,
    MergeStrategy,
    merge_benchmarks,
)
from xpyd_plan.metrics_export import (
    MetricLine,
    MetricsExporter,
    MetricsReport,
    export_metrics,
)
from xpyd_plan.model_compare import (
    ComparisonMatrix,
    ModelComparator,
    ModelComparison,
    ModelProfile,
    ModelRanking,
    compare_models,
)
from xpyd_plan.models import (
    DatasetStats,
    GPUProfile,
    PDConfig,
    SLAConfig,
)
from xpyd_plan.pareto import (
    ParetoAnalyzer,
    ParetoCandidate,
    ParetoFrontier,
    ParetoObjective,
    find_pareto_frontier,
)
from xpyd_plan.pipeline import (
    PipelineConfig,
    PipelineResult,
    PipelineRunner,
    PipelineStep,
    StepResult,
    StepType,
    load_pipeline_config,
    run_pipeline,
)
from xpyd_plan.plan_generator import (
    BenchmarkPlan,
    BenchmarkPlanGenerator,
    PlannedRatio,
    RatioPriority,
    generate_benchmark_plan,
)
from xpyd_plan.plugin import (
    PluginInfo,
    PluginListReport,
    PluginMetadata,
    PluginRegistry,
    PluginSpec,
    PluginType,
    get_plugin,
    get_registry,
    list_plugins,
)
from xpyd_plan.queue_analysis import (
    ConcurrencyPoint,
    ConcurrencyProfile,
    CongestionLevel,
    QueueAnalyzer,
    QueueReport,
    QueueStats,
    analyze_queue,
)
from xpyd_plan.recommender import (
    ActionCategory,
    Recommendation,
    RecommendationEngine,
    RecommendationPriority,
    RecommendationReport,
    get_recommendations,
)
from xpyd_plan.regression import (
    PredictedLatency,
    RegressionAnalyzer,
    RegressionFit,
    RegressionReport,
    analyze_regression,
)
from xpyd_plan.root_cause import (
    CauseFactor,
    FactorSignificance,
    RootCauseAnalyzer,
    RootCauseReport,
    analyze_root_cause,
)
from xpyd_plan.saturation import (
    SaturationDetector,
    SaturationPoint,
    SaturationReport,
    SaturationThreshold,
    detect_saturation,
)
from xpyd_plan.scaling import (
    ScalingAnalyzer,
    ScalingCurve,
    ScalingPoint,
    ScalingReport,
    analyze_scaling,
)
from xpyd_plan.scorecard import (
    ConfigScorecard,
    DimensionScore,
    ScorecardCalculator,
    ScorecardReport,
    ScoreGrade,
    calculate_scorecard,
)
from xpyd_plan.sla_tier import (
    MultiTierReport,
    SLATier,
    SLATierAnalyzer,
    TierResult,
    analyze_sla_tiers,
    load_tiers_from_yaml,
)
from xpyd_plan.tail import (
    LongTailProfile,
    TailAnalyzer,
    TailClassification,
    TailMetric,
    TailReport,
    analyze_tail,
)
from xpyd_plan.threshold_advisor import (
    AdvisorReport,
    PassRateTarget,
    SweetSpot,
    ThresholdAdvisor,
    ThresholdSuggestion,
    advise_thresholds,
)
from xpyd_plan.throughput import (
    ThroughputAnalyzer,
    ThroughputBucket,
    ThroughputReport,
    ThroughputStability,
    ThroughputStats,
    analyze_throughput,
)
from xpyd_plan.timeline import (
    LatencyTrend,
    LatencyTrendDirection,
    TimelineAnalyzer,
    TimelineReport,
    TimeWindow,
    WarmupAnalysis,
    analyze_timeline,
)
from xpyd_plan.token_efficiency import (
    AggregateEfficiency,
    EfficiencyGrade,
    InstanceEfficiency,
    PerRequestEfficiency,
    TokenEfficiencyAnalyzer,
    TokenEfficiencyReport,
    analyze_token_efficiency,
)
from xpyd_plan.trend import TrendEntry, TrendReport, TrendTracker, track_trend
from xpyd_plan.validator import (
    DataQualityScore,
    DataValidator,
    OutlierMethod,
    ValidationResult,
    validate_benchmark,
)
from xpyd_plan.warmup import (
    LatencyComparison,
    WarmupFilter,
    WarmupReport,
    WarmupWindow,
    filter_warmup,
)
from xpyd_plan.workload import (
    WorkloadCategory,
    WorkloadClass,
    WorkloadClassifier,
    WorkloadProfile,
    WorkloadReport,
    classify_workload,
)

__all__ = [
    "AnnotatedBenchmark",
    "Annotation",
    "AnnotationManager",
    "FilterResult",
    "annotate_benchmark",
    "AlertEngine",
    "AlertReport",
    "AlertResult",
    "AlertRule",
    "AlertSeverity",
    "Comparator",
    "evaluate_alerts",
    "AnalysisResult",
    "BenchmarkAnalyzer",
    "BenchmarkComparator",
    "ComparisonResult",
    "MetricDelta",
    "compare_benchmarks",
    "Adequacy",
    "ConfidenceAnalyzer",
    "ConfidenceInterval",
    "ConfidenceReport",
    "MetricConfidence",
    "analyze_confidence",
    "ConvergenceAnalyzer",
    "ConvergencePoint",
    "ConvergenceReport",
    "MetricConvergence",
    "StabilityStatus",
    "analyze_convergence",
    "LoadProfileClassifier",
    "LoadProfile",
    "LoadProfileReport",
    "ProfileType",
    "RateWindow",
    "classify_load_profile",
    "BenchmarkData",
    "BenchmarkMetadata",
    "BenchmarkRequest",
    "ConfigProfile",
    "DatasetStats",
    "GPUProfile",
    "PDConfig",
    "ParetoAnalyzer",
    "ParetoCandidate",
    "ParetoFrontier",
    "ParetoObjective",
    "find_pareto_frontier",
    "RatioCandidate",
    "SLACheck",
    "SLAConfig",
    "UtilizationResult",
    "get_gpu_profile",
    "list_gpu_profiles",
    "load_config",
    "track_trend",
    "TrendEntry",
    "TrendReport",
    "TrendTracker",
    "DataQualityScore",
    "DataValidator",
    "OutlierMethod",
    "ValidationResult",
    "validate_benchmark",
    "InterpolationConfidence",
    "InterpolationMethod",
    "InterpolationResult",
    "PerformanceInterpolator",
    "PredictedPerformance",
    "interpolate_performance",
    "Dashboard",
    "DashboardState",
    "DashboardView",
    "run_dashboard",
    "ActionCategory",
    "Recommendation",
    "RecommendationEngine",
    "RecommendationPriority",
    "RecommendationReport",
    "get_recommendations",
    "PredictedLatency",
    "RegressionAnalyzer",
    "RegressionFit",
    "RegressionReport",
    "analyze_regression",
    "CDFCurve",
    "CDFGenerator",
    "CDFPoint",
    "CDFReport",
    "SLAMarker",
    "generate_cdf",
    "FleetAllocation",
    "FleetCalculator",
    "FleetOption",
    "FleetReport",
    "GPUTypeConfig",
    "calculate_fleet",
    "PipelineConfig",
    "PipelineResult",
    "PipelineRunner",
    "PipelineStep",
    "StepResult",
    "StepType",
    "load_pipeline_config",
    "run_pipeline",
    "MarkdownReportConfig",
    "MarkdownReporter",
    "generate_markdown_report",
    "BenchmarkMerger",
    "MergeConfig",
    "MergeResult",
    "MergeStrategy",
    "merge_benchmarks",
    "ComparisonMatrix",
    "ModelComparator",
    "ModelComparison",
    "ModelProfile",
    "ModelRanking",
    "compare_models",
    "ABTestAnalyzer",
    "ABTestConfig",
    "ABTestReport",
    "ABTestResult",
    "ABConfidenceInterval",
    "EffectMagnitude",
    "EffectSize",
    "PowerWarning",
    "StatisticalTest",
    "analyze_ab_test",
    "AnomalyConfig",
    "AnomalyType",
    "BenchmarkGenerator",
    "DistributionType",
    "GeneratorConfig",
    "LatencyProfile",
    "generate_benchmark",
    "load_generator_config",
    "AllocationStrategy",
    "BudgetAllocation",
    "BudgetAllocator",
    "StageBudget",
    "allocate_budget",
    "BenchmarkFilter",
    "BenchmarkFilterResult",
    "FilterConfig",
    "filter_benchmark",
    "WorkloadCategory",
    "WorkloadClass",
    "WorkloadClassifier",
    "WorkloadProfile",
    "WorkloadReport",
    "LatencyComparison",
    "WarmupFilter",
    "WarmupReport",
    "WarmupWindow",
    "filter_warmup",
    "classify_workload",
    "SaturationDetector",
    "SaturationPoint",
    "SaturationReport",
    "SaturationThreshold",
    "detect_saturation",
    "ScalingAnalyzer",
    "ScalingCurve",
    "ScalingPoint",
    "ScalingReport",
    "analyze_scaling",
    "ConfigScorecard",
    "DimensionScore",
    "ScoreGrade",
    "ScorecardCalculator",
    "ScorecardReport",
    "calculate_scorecard",
    "MetricLine",
    "MetricsExporter",
    "MetricsReport",
    "export_metrics",
    "CorrelationAnalyzer",
    "CorrelationPair",
    "CorrelationReport",
    "CorrelationStrength",
    "analyze_correlation",
    "BucketStats",
    "FairnessAnalyzer",
    "FairnessClassification",
    "FairnessIndex",
    "FairnessReport",
    "analyze_fairness",
    "DriftDetector",
    "DriftReport",
    "DriftResult",
    "DriftSeverity",
    "detect_drift",
    "CauseFactor",
    "FactorSignificance",
    "RootCauseAnalyzer",
    "RootCauseReport",
    "analyze_root_cause",
    "LatencyTrend",
    "LatencyTrendDirection",
    "ThroughputAnalyzer",
    "ThroughputBucket",
    "ThroughputReport",
    "ThroughputStability",
    "ThroughputStats",
    "analyze_throughput",
    "QueueAnalyzer",
    "QueueReport",
    "QueueStats",
    "ConcurrencyProfile",
    "ConcurrencyPoint",
    "CongestionLevel",
    "analyze_queue",
    "AggregateEfficiency",
    "EfficiencyGrade",
    "InstanceEfficiency",
    "PerRequestEfficiency",
    "TokenEfficiencyAnalyzer",
    "TokenEfficiencyReport",
    "analyze_token_efficiency",
    "TimelineAnalyzer",
    "TimelineReport",
    "TimeWindow",
    "WarmupAnalysis",
    "analyze_timeline",
    "LongTailProfile",
    "TailAnalyzer",
    "TailClassification",
    "TailMetric",
    "TailReport",
    "analyze_tail",
    "BenchmarkDiscovery",
    "ConfigGroup",
    "DiscoveredBenchmark",
    "DiscoveryReport",
    "ValidationStatus",
    "discover_benchmarks",
    "AggregationMetric",
    "HeatmapCell",
    "HeatmapConfig",
    "HeatmapGenerator",
    "HeatmapGrid",
    "HeatmapReport",
    "LatencyField",
    "generate_heatmap",
    "CheckResult",
    "HealthChecker",
    "HealthReport",
    "HealthStatus",
    "check_health",
    "BenchmarkPlan",
    "BenchmarkPlanGenerator",
    "PlannedRatio",
    "RatioPriority",
    "generate_benchmark_plan",
    "AdvisorReport",
    "PassRateTarget",
    "SweetSpot",
    "ThresholdAdvisor",
    "ThresholdSuggestion",
    "advise_thresholds",
    "CapacityForecaster",
    "ForecastMethod",
    "ForecastPoint",
    "ForecastReport",
    "CapacityExhaustion",
    "forecast_capacity",
    "SLATier",
    "SLATierAnalyzer",
    "TierResult",
    "MultiTierReport",
    "analyze_sla_tiers",
    "load_tiers_from_yaml",
    "BottleneckType",
    "DecomposedRequest",
    "DecompositionReport",
    "LatencyDecomposer",
    "PhaseStats",
    "decompose_latency",
    "PluginMetadata",
    "PluginRegistry",
    "PluginSpec",
    "PluginType",
    "PluginInfo",
    "PluginListReport",
    "list_plugins",
    "get_plugin",
    "get_registry",
]

from xpyd_plan.summary import (  # noqa: E402
    LatencyOverview,
    SummaryGenerator,
    SummaryReport,
    TokenStats,
    summarize_benchmark,
)

__all__ += [
    "LatencyOverview",
    "SummaryGenerator",
    "SummaryReport",
    "TokenStats",
    "summarize_benchmark",
]

from xpyd_plan.stat_summary import (  # noqa: E402
    AggregatedStats,
    LatencyAggStats,
    RunStability,
    RunSummary,
    StatSummaryAnalyzer,
    StatSummaryReport,
    summarize_stats,
)

__all__ += [
    "AggregatedStats",
    "LatencyAggStats",
    "RunStability",
    "RunSummary",
    "StatSummaryAnalyzer",
    "StatSummaryReport",
    "summarize_stats",
]

from xpyd_plan.outlier_impact import (  # noqa: E402
    ImpactRecommendation,
    ImpactReport,
    MetricImpact,
    OutlierImpactAnalyzer,
    SLAComplianceComparison,
    analyze_outlier_impact,
)

__all__ += [
    "ImpactRecommendation",
    "ImpactReport",
    "MetricImpact",
    "OutlierImpactAnalyzer",
    "SLAComplianceComparison",
    "analyze_outlier_impact",
]

from xpyd_plan.batch_analysis import (  # noqa: E402
    BatchAnalyzer,
    BatchBucket,
    BatchEfficiency,
    BatchReport,
    analyze_batch_impact,
)

__all__ += [
    "BatchAnalyzer",
    "BatchBucket",
    "BatchEfficiency",
    "BatchReport",
    "analyze_batch_impact",
]

from xpyd_plan.roi import (  # noqa: E402
    CostProjection,
    ROICalculator,
    ROIReport,
    SavingsEstimate,
    calculate_roi,
)

__all__ += [
    "CostProjection",
    "ROICalculator",
    "ROIReport",
    "SavingsEstimate",
    "calculate_roi",
]

from xpyd_plan.schema_migrate import (  # noqa: E402
    MigrationResult,
    SchemaMigrator,
    SchemaVersion,
    migrate_schema,
)

__all__ += [
    "MigrationResult",
    "SchemaVersion",
    "SchemaMigrator",
    "migrate_schema",
]

from xpyd_plan.replay import (  # noqa: E402
    ReplayConfig,
    ReplayEntry,
    ReplayGenerator,
    ReplaySchedule,
    generate_replay,
)

__all__ += [
    "ReplayConfig",
    "ReplayEntry",
    "ReplayGenerator",
    "ReplaySchedule",
    "generate_replay",
]
